### ISSUE TITLE
Fabric Defects Dataset links not working

### ISSUE THREAD

**Issue by Aditya-ds-1806** [Charmve/Surface-Defect-Detection#4]
These links don't seem to be working, the page never loads: 
https://pan.baidu.com/s/1cfC4Ll5QlnwN5RTuSZ6b7w
https://pan.baidu.com/s/1LMbujxvr5iB3SwjFGYHspA

**Comment by Charmve** [comment]
Hi, Aditya-ds-1806 

it works in my platform. 

please tell me which dataset you'd like. 

Google Drive is also available - > https://drive.google.com/drive/folders/1q7lirc_yQBXxUSECwX1UvV1TS4eioFm8

Charmve 
maiwei.ai

**Comment by Aditya-ds-1806** [comment]
My bad, the links are working, it seems the servers were not reachable for a while.
